# Generated by Django 5.0.4 on 2025-01-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_alter_category_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_stock',
            field=models.IntegerField(default=0),
        ),
    ]
