# Generated by Django 5.0.4 on 2024-07-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='place',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
