# Generated by Django 5.0.4 on 2024-07-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_register_place_alter_register_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
