# Generated by Django 5.0.4 on 2024-07-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_register_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=100)),
                ('email', models.EmailField(default='null', max_length=100)),
                ('phone', models.CharField(default=0, max_length=100)),
                ('subject', models.CharField(default='null', max_length=20)),
                ('message', models.TextField(default='null')),
            ],
        ),
    ]
