# Generated by Django 5.0.4 on 2024-07-16 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_alter_category_category_image_and_more'),
        ('UserApp', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('usercart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.register')),
                ('userpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.products')),
            ],
        ),
    ]
