# Generated by Django 5.0.4 on 2024-07-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_cart_status_alter_cart_quantity_alter_cart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
