# Generated by Django 5.0.4 on 2024-07-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_alter_cart_quantity_alter_register_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.IntegerField(default=1),
        ),
    ]
