# Generated by Django 5.0.4 on 2024-07-18 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('usercart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.cart')),
                ('usercheckout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.register')),
            ],
        ),
    ]
